version: '3.9'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "9000:5000"
            - "9001:5001"
        volumes:
            - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/development/nginx/auth/htpasswd:/etc/nginx/auth/htpasswd
        depends_on:
            - dockerhub
            - cache-dockerhub

    dockerhub:
        image: registry:2
        volumes:
            - dockerhub:/var/lib/registry

    cache-dockerhub:
        image: registry:2
        restart: always
        environment:
            REGISTRY_PROXY_REMOTEURL: https://dockerhub-1.docker.io
            REGISTRY_STORAGE_DELETE_ENABLED: 1
        volumes:
            - cache-dockerhub:/var/lib/registry

volumes:
    dockerhub:
    cache-dockerhub:
